import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from '../pages/components/NavBar';
import Notificaciones from '../pages/components/Notificaciones';
import AuthWrapper from './AuthWrapper';
import SessionWrapper from './SessionWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Sistema de Gestión de Biblioteca',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <SessionWrapper>
            <AuthWrapper>
                <NavBar />
                <Notificaciones />
                {children}
            </AuthWrapper>
        </SessionWrapper>
        </body>
        </html>
    );
}
